# Исключения

В любой, особенно большой, программе могут возникать ошибки, приводящие к ее неработоспособности или к тому, что программа делает не то, что должна. Причин возникновения ошибок много.

Программист может сделать ошибку в употреблении самого языка программирования. Другими словами, выразиться так, как выражаться не положено. Например, начать имя переменной с цифры или забыть поставить двоеточие в заголовке сложной инструкции. Подобные ошибки называют синтаксическими, они нарушают синтаксис и пунктуацию языка. IDE, встретив ошибочное выражение, не знает как его интерпретировать. Поэтому  выводит соответствующее сообщение, указав на место возникновения ошибки.

Но случаются ошибки, которые происходят во время выполнения программы, например, деление на 0 или попытка открыть несуществующий файл. В таких случаях JVM "выбрасывает" исключение.

На этот случай в языках программирования, в том числе Котлин, существует специальный оператор, позволяющий перехватывать возникающие исключения и обрабатывать их так, чтобы программа продолжала работать или корректно завершала свою работу.

## Классы исключений

Все исключения в Kotlin являются наследниками класса Throwable. У каждого исключения есть сообщение, трассировка стека, а также причина, по которой это исключение вероятно было вызвано.

Обычно исключения вызываются системой (деление на 0, попытка открыть не существующий файл...), но можно и самому возбудить исключение явным образом, для этого используется оператор throw

```kt
throw MyException("Hi There!")
```

## try

Оператор try позволяет перехватывать исключения

```kt
try {
    // при возникновении исключения в этом блоке кода выполнение программы перейдет в блок catch
}
catch (e: SomeException) {
    // handler
}
catch (e: AnotherException) {
    // handler
}
finally {
    // этот блок выполнится всегда
}
```

В коде может быть любое количество блоков catch (такие блоки могут и вовсе отсутствовать). Блоки finally могут быть опущены. Однако, должен быть использован как минимум один блок catch или finally.

## Try - это выражение

Ключевое слово try является выражением, то есть оно может иметь возвращаемое значение.

```kt
val a: Int? = try { parseInt(input) } catch (e: NumberFormatException) { null }
```

Возвращаемым значением будет либо последнее выражение в блоке try, либо последнее выражение в блоке catch (или блоках). Содержимое finally блока никак не повлияет на результат try-выражения.


